/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ibits.telas;

/**
 *
 * @author Ibits
 */
import java.sql.*;
import br.com.ibits.dal.ModuloConexao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//Importando recursos da biblioteca rs2ml.jar
import net.proteanit.sql.DbUtils;

public class TelaCompras extends javax.swing.JInternalFrame {
     Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form TelaCompras
     */
    public TelaCompras() {
        initComponents();
        conexao = ModuloConexao.conector();
        this.popuparCombox();
    }
    
    //Preenchendo ComboBox
    private void popuparCombox(){
    String sql = "Select * from tbprodutos";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
               cboCompMat.addItem(rs.getString("nome"));
            }
            pst.setString(1, (String) cboCompMat.getSelectedItem().toString());
        } catch (Exception e) {
        }
    }
    
     //Salvando Ordem de Compras
    private void Salvar(){
        String sql = "insert into tbCompras(idProd,qtd, medida) Values(?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCompIdProd.getText());
            pst.setString(2, txtCompQtd.getText());
            pst.setString(3, txtCompMed.getText());
            // Validação dos campos obrigatórios
            //Atualiazar tabela Usuario
            //Confirma a inserção dos dados
            int adicionado = pst.executeUpdate();
            //apoio de entedimento
            //System.out.println(adicionado);
            if (adicionado > 0){
               JOptionPane.showMessageDialog(null, "Ordem de compra adicionado com sucesso"); 
                //Limpando os campos
                txtCompQtd.setText(null);
                txtCompMed.setText(null);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }    
   
    //Adcionando produtos na lista
    private void Adicionar(){
        String sql = "insert into tbCompras(qtd, medida,idProd) Values(?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(3, txtCompIdProd.getText());
            pst.setString(1, txtCompQtd.getText());
            pst.setString(2, txtCompMed.getText());
            // Validação dos campos obrigatórios
            if ((txtCompQtd.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios"); 
            }else {
            //Atualiazar tabela Usuario
            //Confirma a inserção dos dado
            int adicionado = pst.executeUpdate();
            //apoio de entedimento
            //System.out.println(adicionado);
            if (adicionado > 0){
               JOptionPane.showMessageDialog(null, "Faccionista adicionado com sucesso"); 
                //Limpando os campos
                txtCompQtd.setText(null); 
            }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    //Setar Campos
    private void setar_Campos(){
         String sql = "Select * from tbCompras";
         try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                cboCompMat.addItem(rs.getString("nome"));
                pst.setString(1, txtCompIdProd.getText());
                pst.setString(2, txtCompQtd.getText());
                pst.setString(3, txtCompMed.getText());
            
              int setar = tblCompras.getSelectedRow();
              txtCompIdProd.setText(tblCompras.getModel().getValueAt(setar, 1).toString());
              pst.setString(2,cboCompMat.getSelectedItem().toString());
              txtCompQtd.setText(tblCompras.getModel().getValueAt(setar, 3).toString());
              txtCompMed.setText(tblCompras.getModel().getValueAt(setar, 4).toString());
              pst.setString(1, (String) cboCompMat.getSelectedItem().toString());
            }
         } catch (SQLException ex) {
             Logger.getLogger(TelaCompras.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCompId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCompQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCompMed = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cboCompMat = new javax.swing.JComboBox<>();
        txtCompIdProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Compras");

        jLabel1.setText("Nº:*");

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod. Produto", "Material", "Quantidade", "Medida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprasMouseClicked(evt);
            }
        });
        tblCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblComprasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblCompras);
        if (tblCompras.getColumnModel().getColumnCount() > 0) {
            tblCompras.getColumnModel().getColumn(0).setMinWidth(90);
            tblCompras.getColumnModel().getColumn(0).setPreferredWidth(90);
            tblCompras.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel2.setText("Material:");

        jLabel3.setText("Qtd:");

        jLabel4.setText("Medida:");

        btnOk.setText("Add");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jButton1.setText("Alterar");

        jButton2.setText("Excluir");

        jLabel5.setText("Cod.Prod:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtCompIdProd, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCompMat, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCompQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCompMed, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnOk)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCompId, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCompQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cboCompMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        setBounds(0, 0, 900, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void tblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseClicked
        // Setando campos
        setar_Campos();
     
    }//GEN-LAST:event_tblComprasMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Salvar dados
        Salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblComprasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblComprasKeyReleased
        // Pesquisa materiais
    }//GEN-LAST:event_tblComprasKeyReleased

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // Adicionando na lista
        Adicionar();
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboCompMat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTextField txtCompId;
    private javax.swing.JTextField txtCompIdProd;
    private javax.swing.JTextField txtCompMed;
    private javax.swing.JTextField txtCompQtd;
    // End of variables declaration//GEN-END:variables
}
